Fill gaps with IoT Central REST apis
Azure/azure-iot-cli-extension pull request #390
Opened 2021-07-12 13:20 UTC by lucadruda

This adds device groups and role listing to IoT Central preview commands in order to align with REST api offer

### General Guidelines

- [x] If introducing new functionality or modified behavior, are they backed by unit and integration tests?
- [x] In the same context as above are command names and their parameter definitions accurate? Do help docs have sufficient content?
- [x] Have **all** unit **and** integration tests passed locally? i.e. `pytest <project root> -vv`
- [x] Have static checks passed using the .pylintrc and .flake8 rules? Look at the CI scripts for example usage.
- [x] Have you made an entry in HISTORY.rst which concisely explains your feature or change?

2021-07-20 15:57 UTC, valluriraj commented on azext_iot/tests/central/test_iot_central_unit.py
>  )
add int tests to the collection.

2021-07-20 20:54 UTC, valluriraj requested changes
add integration tests to cover E2E scenarios

2021-07-21 18:29 UTC, valluriraj approved these changes

2021-07-21 19:34 UTC, c-ryan-k approved these changes

2021-07-21 20:01 UTC, merged